import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  SafeAreaView,
  StatusBar,
  TouchableOpacity,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";

const safetyCategories = [
  {
    id: "before",
    title: "Before Travel",
    subtitle: "Prepare before starting your journey",
    icon: "briefcase-outline",
    tips: [
      "Share your travel plan with a trusted family member or friend.",
      "Save important emergency numbers before travelling.",
      "Keep digital and physical copies of your ID and travel documents.",
      "Check weather conditions before starting your journey.",
      "Keep your phone fully charged.",
      "Carry a power bank during long journeys.",
    ],
  },

  {
    id: "location",
    title: "Location & Geofencing",
    subtitle: "Stay aware of your surroundings",
    icon: "location-outline",
    tips: [
      "Keep location services enabled when using safety features.",
      "Pay attention to Safe, Moderate and Danger zone alerts.",
      "Avoid unfamiliar restricted or high-risk areas.",
      "Follow alerts generated by the Safe Tourism system.",
      "Download offline maps before travelling to remote areas.",
      "Know the location of the nearest hospital and police station.",
    ],
  },

  {
    id: "travel",
    title: "During Travel",
    subtitle: "Stay alert while exploring",
    icon: "walk-outline",
    tips: [
      "Avoid isolated roads and unknown shortcuts.",
      "Use trusted transportation services.",
      "Do not accept food, drinks or rides from strangers.",
      "Keep your belongings secure in crowded places.",
      "Stay aware of your surroundings.",
      "Avoid travelling alone in unfamiliar areas at night.",
    ],
  },

  {
    id: "emergency",
    title: "Emergency Safety",
    subtitle: "Know what to do during an emergency",
    icon: "warning-outline",
    tips: [
      "Stay calm and assess the situation.",
      "Move towards a safe and populated location.",
      "Contact a trusted emergency contact.",
      "Contact the nearest police station or hospital.",
      "Share your current location when asking for help.",
      "Keep important emergency numbers easily accessible.",
    ],
  },

  {
    id: "cyber",
    title: "Personal & Cyber Safety",
    subtitle: "Protect your identity and information",
    icon: "shield-checkmark-outline",
    tips: [
      "Avoid connecting to unknown public Wi-Fi networks.",
      "Never share OTPs, passwords or banking PINs.",
      "Use strong passwords for important accounts.",
      "Avoid suspicious links and unknown QR codes.",
      "Enable two-factor authentication.",
      "Do not publicly share your exact live location.",
    ],
  },

  {
    id: "family",
    title: "Family & Group Safety",
    subtitle: "Keep your travel group connected",
    icon: "people-outline",
    tips: [
      "Keep your family informed about your travel plans.",
      "Set a meeting point if someone gets separated.",
      "Share your location with trusted people when required.",
      "Keep children and elderly travellers within sight.",
      "Make sure everyone knows the emergency procedure.",
      "Check on group members during long journeys.",
    ],
  },

  {
    id: "destination",
    title: "Destination Safety",
    subtitle: "Stay informed about your destination",
    icon: "earth-outline",
    tips: [
      "Learn about local rules and regulations.",
      "Check weather and environmental conditions.",
      "Identify nearby hospitals and police stations.",
      "Avoid restricted or unauthorized areas.",
      "Ask verified local authorities for information.",
      "Keep local emergency numbers available.",
    ],
  },
];

export default function SafetyTips() {
  const [expanded, setExpanded] = useState("before");

  const toggleCategory = (id: string) => {
    if (expanded === id) {
      setExpanded("");
    } else {
      setExpanded(id);
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* HEADER */}

        <View style={styles.header}>
          <View>
            <Text style={styles.smallTitle}>
              TRAVEL SMART • STAY SAFE
            </Text>

            <Text style={styles.title}>
              Safety Tips
            </Text>

            <Text style={styles.subtitle}>
              Simple precautions for a safer journey
            </Text>
          </View>

          <View style={styles.headerIcon}>
            <Ionicons
              name="shield-checkmark"
              size={28}
              color="#00D4FF"
            />
          </View>
        </View>

        {/* SAFETY CARD */}

        <View style={styles.safetyCard}>
          <View style={styles.safetyIcon}>
            <Ionicons
              name="shield-checkmark"
              size={30}
              color="#00D4FF"
            />
          </View>

          <View style={styles.safetyContent}>
            <Text style={styles.safetyLabel}>
              TRAVEL SAFETY
            </Text>

            <Text style={styles.safetyTitle}>
              Stay Alert. Stay Safe.
            </Text>

            <Text style={styles.safetyText}>
              Follow these safety practices while exploring new
              places.
            </Text>
          </View>
        </View>

        {/* EMERGENCY CARD */}

        <View style={styles.emergencyCard}>
          <View style={styles.emergencyIcon}>
            <Ionicons
              name="alert-circle"
              size={28}
              color="#FF5C6C"
            />
          </View>

          <View style={styles.emergencyContent}>
            <Text style={styles.emergencyTitle}>
              Emergency?
            </Text>

            <Text style={styles.emergencyText}>
              Stay calm and move towards a safe location.
              Emergency SOS will be available here.
            </Text>
          </View>
        </View>

        {/* SECTION TITLE */}

        <View style={styles.sectionHeader}>
          <View>
            <Text style={styles.sectionTitle}>
              Safety Guide
            </Text>

            <Text style={styles.sectionSubtitle}>
              Tap a category to view important tips
            </Text>
          </View>

          <View style={styles.countBox}>
            <Text style={styles.countText}>
              {safetyCategories.length}
            </Text>
          </View>
        </View>

        {/* SAFETY CATEGORIES */}

        {safetyCategories.map((category) => {
          const isExpanded = expanded === category.id;

          return (
            <View
              key={category.id}
              style={[
                styles.categoryCard,
                isExpanded && styles.activeCategory,
              ]}
            >
              {/* CATEGORY HEADER */}

              <TouchableOpacity
                activeOpacity={0.8}
                onPress={() => toggleCategory(category.id)}
                style={styles.categoryHeader}
              >
                <View style={styles.categoryIcon}>
                  <Ionicons
                    name={category.icon as any}
                    size={23}
                    color="#00D4FF"
                  />
                </View>

                <View style={styles.categoryInfo}>
                  <Text style={styles.categoryTitle}>
                    {category.title}
                  </Text>

                  <Text style={styles.categorySubtitle}>
                    {category.subtitle}
                  </Text>
                </View>

                <View style={styles.arrowBox}>
                  <Ionicons
                    name={
                      isExpanded
                        ? "chevron-up"
                        : "chevron-down"
                    }
                    size={18}
                    color="#8E94A7"
                  />
                </View>
              </TouchableOpacity>

              {/* TIPS */}

              {isExpanded && (
                <View style={styles.tipsContainer}>
                  {category.tips.map((tip, index) => (
                    <View
                      key={index}
                      style={styles.tipRow}
                    >
                      <View style={styles.numberCircle}>
                        <Text style={styles.numberText}>
                          {index + 1}
                        </Text>
                      </View>

                      <Text style={styles.tipText}>
                        {tip}
                      </Text>
                    </View>
                  ))}
                </View>
              )}
            </View>
          );
        })}

        {/* QUICK REMINDER */}

        <View style={styles.reminderCard}>
          <View style={styles.reminderHeader}>
            <Ionicons
              name="bulb-outline"
              size={24}
              color="#00D4FF"
            />

            <Text style={styles.reminderTitle}>
              Quick Safety Reminder
            </Text>
          </View>

          <Text style={styles.reminderText}>
            Trust your instincts. If a place or situation
            feels unsafe, leave the area and move towards a
            safe and populated location.
          </Text>
        </View>

        {/* FOOTER */}

        <View style={styles.footer}>
          <Ionicons
            name="shield-outline"
            size={18}
            color="#666D80"
          />

          <Text style={styles.footerText}>
            Explore freely. Stay connected. Travel safely.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#070B18",
  },

  scrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 35,
  },

  /* HEADER */

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 15,
    marginBottom: 22,
  },

  smallTitle: {
    color: "#00D4FF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.4,
    marginBottom: 5,
  },

  title: {
    color: "#FFFFFF",
    fontSize: 29,
    fontWeight: "800",
  },

  subtitle: {
    color: "#858B9E",
    fontSize: 13,
    marginTop: 5,
  },

  headerIcon: {
    width: 54,
    height: 54,
    borderRadius: 17,
    backgroundColor: "#11182B",
    borderWidth: 1,
    borderColor: "#1D2B45",
    alignItems: "center",
    justifyContent: "center",
  },

  /* SAFETY CARD */

  safetyCard: {
    flexDirection: "row",
    backgroundColor: "#0D1426",
    borderRadius: 20,
    padding: 17,
    borderWidth: 1,
    borderColor: "#192743",
    marginBottom: 15,
  },

  safetyIcon: {
    width: 56,
    height: 56,
    borderRadius: 17,
    backgroundColor: "#101F35",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },

  safetyContent: {
    flex: 1,
  },

  safetyLabel: {
    color: "#00D4FF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },

  safetyTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 4,
  },

  safetyText: {
    color: "#858B9E",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },

  /* EMERGENCY */

  emergencyCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#17111D",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3A202E",
    padding: 15,
    marginBottom: 26,
  },

  emergencyIcon: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: "#261722",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },

  emergencyContent: {
    flex: 1,
  },

  emergencyTitle: {
    color: "#FF6B78",
    fontSize: 15,
    fontWeight: "800",
  },

  emergencyText: {
    color: "#9993A1",
    fontSize: 11,
    lineHeight: 17,
    marginTop: 3,
  },

  /* SECTION */

  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 13,
  },

  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 19,
    fontWeight: "800",
  },

  sectionSubtitle: {
    color: "#71788C",
    fontSize: 11,
    marginTop: 3,
  },

  countBox: {
    width: 31,
    height: 31,
    borderRadius: 10,
    backgroundColor: "#111A2E",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#20304C",
  },

  countText: {
    color: "#00D4FF",
    fontSize: 12,
    fontWeight: "800",
  },

  /* CATEGORY */

  categoryCard: {
    backgroundColor: "#0D1426",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#18243B",
    marginBottom: 11,
    overflow: "hidden",
  },

  activeCategory: {
    borderColor: "#243B60",
  },

  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
  },

  categoryIcon: {
    width: 47,
    height: 47,
    borderRadius: 14,
    backgroundColor: "#101D32",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },

  categoryInfo: {
    flex: 1,
  },

  categoryTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },

  categorySubtitle: {
    color: "#737A8D",
    fontSize: 11,
    marginTop: 4,
  },

  arrowBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
  },

  /* TIPS */

  tipsContainer: {
    paddingHorizontal: 14,
    paddingBottom: 15,
    paddingTop: 2,
    borderTopWidth: 1,
    borderTopColor: "#172239",
  },

  tipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 13,
  },

  numberCircle: {
    width: 25,
    height: 25,
    borderRadius: 8,
    backgroundColor: "#111E34",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 1,
  },

  numberText: {
    color: "#00D4FF",
    fontSize: 10,
    fontWeight: "800",
  },

  tipText: {
    flex: 1,
    color: "#B6BBC8",
    fontSize: 12,
    lineHeight: 19,
  },

  /* REMINDER */

  reminderCard: {
    backgroundColor: "#0D1426",
    borderRadius: 19,
    padding: 17,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#1C2B44",
  },

  reminderHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },

  reminderTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    marginLeft: 9,
  },

  reminderText: {
    color: "#8B92A5",
    fontSize: 12,
    lineHeight: 19,
  },

  /* FOOTER */

  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 24,
  },

  footerText: {
    color: "#666D80",
    fontSize: 11,
    marginLeft: 7,
  },
});